default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  host: localhost

development:
  <<: *default
  database: twitter-clone_development

test: &test
  <<: *default
  database: twitter-clone_test
  min_messages: WARNING
